[Golder]
TEMP = ''

[Database]
# Which driver to use for the database.
# # "sqlite", "mysql", "postgres"
DB_DRIVER = 'sqlite'
# URI to connect to the database.
DB_URI = 'golder.db'

[Authentication]
# Do not change this key once set.
SECRET_KEY = 'fb08c8e7f6e1f7f9e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855'

